#ifndef _VOLUME_HPP_INCLUDED_FOSDIJ3098USFLKJ4098USFDLIJ49O8ILFDSIKJLVSFDOI3498SFDLIJLSFKDJALKJLSKJFCKMVNJKLDFLKJF
#define _VOLUME_HPP_INCLUDED_FOSDIJ3098USFLKJ4098USFDLIJ49O8ILFDSIKJLVSFDOI3498SFDLIJLSFKDJALKJLSKJFCKMVNJKLDFLKJF

#include <tri_ary.hpp>

namespace feng
{
    template<typename T>
    T volume( const tri_ary<T>& a, const tri_ary<T>& b, const tri_ary<T>& c )
    {
        return dot_product( a, crossproduct( b, c ) );
    }

}//namespace feng

#endif//_VOLUME_HPP_INCLUDED_FOSDIJ3098USFLKJ4098USFDLIJ49O8ILFDSIKJLVSFDOI3498SFDLIJLSFKDJALKJLSKJFCKMVNJKLDFLKJF

